@startuml




participant "Origin Country\nHIE" as OCHIE
participant "GHDCN\nTrust Anchor" as TA
participant "Host Country\nProxy" as HCP
participant "Origin Country\nHIE" as OCHIE
participant "Pilgrim" as P

participant "Host Country\nEMR" as HCEMR



autonumber "<b>00:</b>"



== Key Generation Host Country ==
HP -> HP : generate public-private key pairs\nfor mTLS connection\n(Data Exchange Signing Certficate - DESC)
HP  -> TA: send public keys\nfor DESCs


note right
	Onboarding:All DESCs should be generated subordinate to a
	Data Exchange Certificate Authority (DECA) prior
	to uploading to the Trust Anchor
end note


== Key Generation Origin Country ==
OCHIE -> OCHIE : generate public-private key pairs\nfor mTLS connection\n(Data Exchange Signing Certficate - DESC)
OCHIE -> OCHIE : generate public-private key pairs\nfor singnture verificaiton\n(Document Signing Certificate - DSC)
OCHIE -> TA: send public keys\nfor DESCs and DSCs


note right
	Onboarding: All DSCs should be generated subordinate to a
	Document Signing Certificate Authority (DSCA) prior
	to uploading to the Trust Anchor
end note


== Routine Synchronization ==
  HCP -> TA : retrieves and caches all DESC public keys
  HCEMR -> TA : retrieves and caches all DSC public keys



== Utiliztion of VHL ==

OCIE -> P : Issue VHL
P -> HCEMR : Provide (show) VHL
HCEMR -> HCEMR : Extract VHL payload
HCEMR -> HCEMR : Validate VHL signature\nusing DESC associated to\nVHL key ID (kid)


== Proxy Request ==

HCEMR -> HP : Send VHL payload
HP -> HP : Extract URL from VHL Payload
HP -> HP : Determine Origin Country of VHL
HP -> HP : Retrieve DESC(s) from Origin Country
HP -> OCHIE : Initiate connection to URL in VHL payload\nproviding DESC
OCHIE -> OCHIE : Validate Host Country DESC
OCHIE -> HP : Respond to connection request\nproviding DESC
HP -> HP : Validate Origin Country DESC
HP -> HCEMR : Forward OCHIE response


@enduml
