@startuml

title Health Assessment, Consent Counselling,  and Issuance of Smart Health Link at Malaysia
!include ./style.iuml

actor "Hajj Counselor" as C
actor "Pilgrim from\nOrigin Country" as P
participant "Origin Country\nHealth Wallet\nMySejahtera" as HW
participant "Origin Country\nHajj Health Screening Repository" as OCHIE
participant "QR Code" as QR
autonumber "<b>00:</b>"


group Asessment
   C -> P : conduct health assessment\nutilize FHIR Questionnaire resource for UI
   C -> OCHIE : store Assesment response as\nFHIR QuestionnaireResponse resource
   OCHIE -> OCHIE : Assessment QuestionaireResponse extracted to\n corresponding FHIR resource 
end

group Counseling and Consent
  	C -> P : explain utilization of digital health wallet\nduring Hajj including consent policy 
end

group Issue Smart Health Link
	note left of QR #aqua
   	  Verifiable Smart Health Links:
	  create Smart Health Link for the IPS
	  generate digital signature\ncapture signed SHL as HCERT claim
	  HCERT is rendered as QR code
	end note
   P -> HW : generate IPS from the FHIR resource through MySejhatera app\n standard disclosure & timelimit is set by system
   HW -> HW : display Consent Questionniare as\n FHIR Questionnaire resource for UI
   HW -> OCHIE:  Consent stored as QuestionnaireResponse
   OCHIE -> OCHIE: Consent QuestionnaireResponse extracted and \nCreate Consent resource with codes\n#CONSENT-KSA and #CONSENT-MYS
   OCHIE -> OCHIE: Add the consent FHIR resource to IPS
      HW -> OCHIE : request verifiable HCERT SHL for  IPS\nSend Consent Questionniare
   OCHIE -> OCHIE : generate Verifiable Smart Health Link
end



@enduml
