@startuml

!include ./style.iuml


participant "Host Country\nEMR" as HCEMR
participant "Origin Country\nHIE" as OCHIE
autonumber "<b>00:</b>"

HCEMR -> OCHIE : retrieve MHD folder docs request
OCHIE -> HCEMR : send MHD folder docs request response

@enduml