@startuml

title Routine Synchronization
!include ./style.iuml
participant "Origin Country\nHealth Wallet" as OC
participant "Origin Country\nHIE" as OCHIE
participant "WHO GDHCN" as WHO
participant "Host Country\nEMR" as HCEMR


autonumber "<b>00:</b>"


loop routine synchronization 
  OC -> OC : generate public-private key pairs\nfor issuing health documents
  OCHIE -> WHO: send public keys\nfor IPS verification
  HCEMR -> WHO : retrieves and caches all public keys\nfor IPS and VHL verification
end

@enduml
