@startuml
skinparam svgDimensionStyle false

title Religious Pilgrimage and IPS

actor "Pilgrim from\nOrigin Country" as P
participant "Origin Country\nHealth Wallet" as OC
participant "Origin Country\nHIE" as OCHIE
participant "WHO GDHCN" as WHO
participant "Host Country\nHIE" as HCHIE
participant "Host Country\nEMR" as HCEMR
actor "Health Worker\nin Host Country" as HW

autonumber "<b>00:</b>"


loop routine synchronization 
  OC -> OC : generate public-private key pairs\nfor issuing health documents
  OCHIE -> WHO: send public keys\nfor IPS verification
  HCEMR -> WHO : retrieves and caches all public keys\nfor IPS and SHL verification
end
destroy WHO

P -> OC  : request health document\nwith selective disclosure,\ntime limits and passcode
OC -> OCHIE : request health document

OCHIE  -> OCHIE : generate health document\ncreate signature with private key\nattach signature and keyid
OCHIE -> OC : issue verifiable health document\n(IPS via SHL)

P --> HW: travels to Host Country and seeks care,\nshares verifiable health document from\nhealth wallet (IPS via SHL),\nshares pilgrimage number
HW --> HCEMR: registers patient with pilgrimage number
HW --> HCEMR: scans QR code within EMR
HCEMR -> OC: scans QR code from\npilgrim's health wallet\n(IPS via SHL)
destroy OC
HCEMR -> HCEMR: verifies QR code signature
HCEMR  -> OCHIE : retrieves health document
destroy OCHIE


HCEMR-> HCEMR: verifies health document signature\n using cached keys
HCEMR -> HCEMR: saves local copy of health document
HCEMR-> HCHIE: upload health document\nassociated with pilgrimage number
HCEMR->HW: display contents of health document
 
HW --> P: provides appropriate care
HW -> HCEMR: updates local record of care
HCEMR->HCHIE: updates national record of care

@enduml
