@startuml

title Clinical Encounter for Unplanned Care with HIE
!include ./style.iuml
actor "Pilgrim from\nOrigin Country" as P
participant "Origin Country\nHealth Wallet" as OC
participant "Origin Country\nHIE" as OCHIE
participant "Host Country\nHIE" as HCHIE
participant "Host Country\nEMR" as HCEMR
actor "Health Worker\nin Host Country" as HW

autonumber "<b>00:</b>"

P --> HW: travels to Host Country and seeks care,\nshares verifiable health document from\nhealth wallet (IPS via SHL),\nshares pilgrimage number
HW --> HCEMR: registers patient with pilgrimage number
HW --> HCEMR: scans QR code within EMR
HCEMR -> OC: scans QR code from\npilgrim's health wallet\n(IPS via SHL)
destroy OC
HCEMR -> HCEMR: verifies QR code signature\n using cached keys
HCEMR  -> OCHIE : retrieves health document\n(document might be pregenerated\n or generated on request)
destroy OCHIE


HCEMR-> HCEMR: verifies health document signature\n using cached keys
HCEMR -> HCEMR: saves local copy of health document
HCEMR-> HCHIE: upload health document\nassociated with pilgrimage number
HCEMR->HW: display contents of health document
 
HW --> P: provides appropriate care
HW -> HCEMR: updates local record of care
HCEMR->HCHIE: updates national record of care

@enduml
